### ISSUE TITLE
Document phantomjs runner

### ISSUE THREAD

**Issue by cburgmer** [cburgmer/csscritic#13]
How to run.

**Comment by SamHasler** [comment]
Do you mean this: https://github.com/cburgmer/csscritic/issues/15#issuecomment-48760860 ?

**Comment by SamHasler** [comment]
Given I have run:
```
npm install csscritic
npm install -g phantomjs
cd node_modules/csscritic
```
When I run `phantomjs dist/csscritic-phantom.js --log="log/" example/*.html` it hangs. 

What do I need to do to get this to work?

**Comment by cburgmer** [comment]
I can confirm that. It currently only seems to work if you specify a sign-off json document, similar as to what happens inside the `./go` script.

**Comment by cburgmer** [comment]
Closing as I'm not planning to bring this forward.
