### ISSUE TITLE
Only use the reference image of the signed off version

### ISSUE THREAD

**Issue by cburgmer** [cburgmer/csscritic#16]
If a version valid in the past is changed to be invalid (change in what the user accepts) an old reference image might still pass the test. Reference images should be linked to a particular signed off version.

**Comment by SamHasler** [comment]
Would it be better to do it the other way around? i.e. fingerprint the image and link signed of versions to reference images?

**Comment by cburgmer** [comment]
Closing as I'm not planning to bring this forward.
