### ISSUE TITLE
rasterizeHTML.js DOMParser errors are not reported to the user

### ISSUE THREAD

**Issue by SamHasler** [cburgmer/csscritic#65]
If you have a tag like  `<namespace:customtag></ namespace:customtag>` in the test it will silently fail to run.

This is a [known limitaion of rasterizeHTML](https://github.com/cburgmer/rasterizeHTML.js/wiki/Limitations#yet-unsupported-html):

> HTML elements may only contain colons if the prefix is treated as a namespace and has it declared as it would be in XHTML

However it would be helpful if CSSCritic alerted the user that the DOMParser failed.

The DOMParser is here:

https://github.com/cburgmer/rasterizeHTML.js/blob/dd68b6eb97b6446c17a5b1e2d40cbb1430255638/src/browser.js#L219

**Comment by cburgmer** [comment]
Hey, I just committed a small change that renders error messages with a failed test case. Any message from rasterizeHTML will now be directly passed through to the user.

Now it starts getting complicated though.

Currently it will just report "Invalid source".

If you read http://stackoverflow.com/questions/11563554/how-do-i-detect-xml-parsing-errors-when-using-javascripts-domparser-in-a-cross and https://developer.mozilla.org/en-US/docs/Web/API/DOMParser you will quickly find out that browser's don't provide a machine-friendly way for finding out about parsing errors. So getting the failing piece and the error message is not trivial.

If you are interested, this sounds like a nice and small JS package for just guessing the error format of the respective browser and constructing a proper error object.

**Comment by cburgmer** [comment]
Something like this https://github.com/cburgmer/sane-domparser/

**Comment by cburgmer** [comment]
This is now integrated in rasterizeHTML https://github.com/cburgmer/rasterizeHTML.js/commit/4a9201677c95a53a42b30619e730078711fd0254

**Comment by cburgmer** [comment]
I have now changed the API in rasterizeHTML to return the original error object `{message: '...', originalError: e}` if it exists. This will require a change in csscritic to make use of that.

The error from the DOM parsing as returned by sane-domparser can surely do with more love, e.g. providing the actual failing source, and support for the new Edge browser.

Let me know what you think & and maybe have a go at my changes.

**Comment by cburgmer** [comment]
With the new release of rasterizehtml, I've now added the necessary change here to pick up on the underlying error.

While this can certainly be improved upon (https://github.com/cburgmer/sane-domparser-error/issues/1), I feel your original request is answered. Let me know if we are missing something or the issue can be closed.

I'll then also make a new release here.

**Comment by cburgmer** [comment]
I'm closing this for now. The errors can certainly be made more beautiful/more telling, but that's optional I believe, and we can pick this up in the future. Thanks!
