### ISSUE TITLE
Problem with new firefox version

### ISSUE THREAD

**Issue by mazzeb** [cburgmer/csscritic#67]
Hey, it seems that there is a problem with the latest firefox version. We always get the "The page could not be rendered" error. We had the same setup working before the firefox update.

**Comment by cburgmer** [comment]
That doesn't sound too good.

I just upgraded to Firefox 41.0 on Mac OSX and http://cburgmer.github.io/csscritic-examples/angularjs/ continues to render well for me. Existing reference images are correctly compared, and after clearing the indexedDB (`indexedDB.deleteDatabase('csscritic')`) newly generated reference images also work as expected. The local setup of csscritic itself (https://github.com/cburgmer/csscritic/blob/master/RegressionRunner.html) also works for me.

Can you cross check the first link, and if that works, maybe provide more details on your setup?

**Comment by mazzeb** [comment]
Thanks for the fast answer. I have no idea what exactly broke, but maybe it was a messed up indexDB after the update. However its working again.

**Comment by cburgmer** [comment]
Nice :)
