### ISSUE TITLE
place accept button to the left side

### ISSUE THREAD

**Issue by edouard-lopez** [cburgmer/csscritic#71]
Placing it on the left make it obvious, while on the right it make the **button invisible as it behind the viewport** (e.g. 15" screen with 1366x768 image).

**Comment by SamHasler** [comment]
It would also then be in a consistent position when scrolling.

**Comment by cburgmer** [comment]
Thanks, valuable feedback!

If we position the button to the left, either by default all images are offset to the right by the necessary margin, or at least the ones on failing comparisons (to make place for the button). I'll try it out.

**Comment by cburgmer** [comment]
I moved the button to the left and the images to the right. Happy for feedback on how that feels!

**Comment by edouard-lopez** [comment]
look good to me. Thanks

**Comment by cburgmer** [comment]
Thanks everybody!
