### ISSUE TITLE
How to use slimerjs?

### ISSUE THREAD

**Issue by edouard-lopez** [cburgmer/csscritic#75]
I see in the `package.json` that `slimerjs` is a dependencies yet I can't find documentation on how to use it.

Could you provide some info on this topic?

**Comment by cburgmer** [comment]
It listed under `devDependencies` and only used for smoke testing, for example if you run `grunt shell:smokeTestBundle`.

**Comment by edouard-lopez** [comment]
So no screenshot capabilities at the moment.

**Comment by cburgmer** [comment]
I am trying to describe the mission of csscritic in https://github.com/cburgmer/csscritic#how-is-it-different-to-the-other-tools-out-there. I probably have to give it yet another iteration.

In my experiences of the past years I'd always value the quick and lightweight feedback over a rigorous, yet heavyweight tool. This in fact means: I'm trying to focus on making csscritic give feedback in under 10 seconds, in a quick change-evaluate-reload loop. I'm not trying to solve the problem of preventing failures in a build pipeline or issues arising from integrating different systems at the front end level. Long story short: running UI tests in Firefox and Chrome (hopefully other browsers in the future) to me is still the best option to achieve this goal.

**Comment by edouard-lopez** [comment]
Having a quick feedback loop is an excellent choice.

I was asking this cause I detected visual regression smaller `chrome` device but had to manually check on Firefox.

Wait… I might be confused, does your screenshots happen in a PhantomJS instance or in the browser opening the page?

**Comment by cburgmer** [comment]
Everything is rendered in the browser. A lot of work went into handling this in https://github.com/cburgmer/rasterizeHTML.js. This makes csscritic unique, as all the other tools try to solve the problem outside of the browser.

**Comment by cburgmer** [comment]
Closing as the question seems answered.
