### ISSUE TITLE
don't show warning about same origin policy if CORS has been setup

### ISSUE THREAD

**Issue by thedavidmeister** [cburgmer/csscritic#80]
I'm using CORS to work around the same origin policy.

CSS critic should not show the warning about same origin if CORS is set.

**Comment by cburgmer** [comment]
Fair point! Any ideas how we could do that? Currently the check is rather trivial: https://github.com/cburgmer/csscritic/blob/master/src/reporter/niceReporter.js#L677

Would a "don't bother me" button help, which remembers via cookie/localStorage?

I have to ask though, are you using Safari? Both Chrome and Firefox in recent versions should not flag this warning at all.

**Comment by cburgmer** [comment]
Sorry, I might have been mistaken. Are you rather talking about this warning: https://github.com/cburgmer/csscritic/blob/master/src/reporter/niceReporter.js#L636 ?

**Comment by thedavidmeister** [comment]
@cburgmer sorry, no longer working on the project where this was an issue, so I've sort of forgotten the details >.<

**Comment by cburgmer** [comment]
NP, I'll close this for now. Thanks!
